"""empty message

Revision ID: 157d3c6078a0
Revises: 486d920bc441
Create Date: 2020-08-18 19:32:03.261788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '157d3c6078a0'
down_revision = '486d920bc441'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('earf',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('EARF_Number', sa.Integer(), nullable=False),
    sa.Column('EARF_Date', sa.DateTime(), nullable=True),
    sa.Column('Case_Nature_Code', sa.String(length=100), nullable=True),
    sa.Column('Case_Nature', sa.String(length=300), nullable=True),
    sa.Column('Dangers', sa.Text(), nullable=True),
    sa.Column('Address', sa.String(length=500), nullable=True),
    sa.Column('Road_Class', sa.String(length=100), nullable=True),
    sa.Column('Road_Type', sa.String(length=100), nullable=True),
    sa.Column('Road_Importance', sa.Float(), nullable=True),
    sa.Column('Lat', sa.Float(), nullable=True),
    sa.Column('Lon', sa.Float(), nullable=True),
    sa.Column('Final_Assessment_Code', sa.String(length=100), nullable=True),
    sa.Column('Final_Assessment', sa.String(length=300), nullable=True),
    sa.Column('Patient_Ages', sa.Integer(), nullable=True),
    sa.Column('Patient_Gender', sa.Integer(), nullable=True),
    sa.Column('Time_Received', sa.DateTime(), nullable=True),
    sa.Column('Time_On_Scene', sa.DateTime(), nullable=True),
    sa.Column('Response_Time', sa.Integer(), nullable=True),
    sa.Column('Response_Time_Class', sa.Integer(), nullable=True),
    sa.Column('Case_Comments', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_earf_Address'), 'earf', ['Address'], unique=False)
    op.create_index(op.f('ix_earf_Case_Nature'), 'earf', ['Case_Nature'], unique=False)
    op.create_index(op.f('ix_earf_Case_Nature_Code'), 'earf', ['Case_Nature_Code'], unique=False)
    op.create_index(op.f('ix_earf_EARF_Date'), 'earf', ['EARF_Date'], unique=False)
    op.create_index(op.f('ix_earf_EARF_Number'), 'earf', ['EARF_Number'], unique=False)
    op.create_index(op.f('ix_earf_Final_Assessment'), 'earf', ['Final_Assessment'], unique=False)
    op.create_index(op.f('ix_earf_Final_Assessment_Code'), 'earf', ['Final_Assessment_Code'], unique=False)
    op.create_index(op.f('ix_earf_Lat'), 'earf', ['Lat'], unique=False)
    op.create_index(op.f('ix_earf_Lon'), 'earf', ['Lon'], unique=False)
    op.create_index(op.f('ix_earf_Patient_Ages'), 'earf', ['Patient_Ages'], unique=False)
    op.create_index(op.f('ix_earf_Patient_Gender'), 'earf', ['Patient_Gender'], unique=False)
    op.create_index(op.f('ix_earf_Response_Time'), 'earf', ['Response_Time'], unique=False)
    op.create_index(op.f('ix_earf_Response_Time_Class'), 'earf', ['Response_Time_Class'], unique=False)
    op.create_index(op.f('ix_earf_Road_Class'), 'earf', ['Road_Class'], unique=False)
    op.create_index(op.f('ix_earf_Road_Importance'), 'earf', ['Road_Importance'], unique=False)
    op.create_index(op.f('ix_earf_Road_Type'), 'earf', ['Road_Type'], unique=False)
    op.create_index(op.f('ix_earf_Time_On_Scene'), 'earf', ['Time_On_Scene'], unique=False)
    op.create_index(op.f('ix_earf_Time_Received'), 'earf', ['Time_Received'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_earf_Time_Received'), table_name='earf')
    op.drop_index(op.f('ix_earf_Time_On_Scene'), table_name='earf')
    op.drop_index(op.f('ix_earf_Road_Type'), table_name='earf')
    op.drop_index(op.f('ix_earf_Road_Importance'), table_name='earf')
    op.drop_index(op.f('ix_earf_Road_Class'), table_name='earf')
    op.drop_index(op.f('ix_earf_Response_Time_Class'), table_name='earf')
    op.drop_index(op.f('ix_earf_Response_Time'), table_name='earf')
    op.drop_index(op.f('ix_earf_Patient_Gender'), table_name='earf')
    op.drop_index(op.f('ix_earf_Patient_Ages'), table_name='earf')
    op.drop_index(op.f('ix_earf_Lon'), table_name='earf')
    op.drop_index(op.f('ix_earf_Lat'), table_name='earf')
    op.drop_index(op.f('ix_earf_Final_Assessment_Code'), table_name='earf')
    op.drop_index(op.f('ix_earf_Final_Assessment'), table_name='earf')
    op.drop_index(op.f('ix_earf_EARF_Number'), table_name='earf')
    op.drop_index(op.f('ix_earf_EARF_Date'), table_name='earf')
    op.drop_index(op.f('ix_earf_Case_Nature_Code'), table_name='earf')
    op.drop_index(op.f('ix_earf_Case_Nature'), table_name='earf')
    op.drop_index(op.f('ix_earf_Address'), table_name='earf')
    op.drop_table('earf')
    # ### end Alembic commands ###
