"""empty message

Revision ID: 5d39d4ca596a
Revises: 449202edffb8
Create Date: 2020-10-12 19:59:14.595765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d39d4ca596a'
down_revision = '449202edffb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clustering',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('EARF_Number', sa.Integer(), nullable=False),
    sa.Column('Lat', sa.Float(), nullable=True),
    sa.Column('Lon', sa.Float(), nullable=True),
    sa.Column('Label', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clustering_EARF_Number'), 'clustering', ['EARF_Number'], unique=False)
    op.create_index(op.f('ix_clustering_Label'), 'clustering', ['Label'], unique=False)
    op.create_index(op.f('ix_clustering_Lat'), 'clustering', ['Lat'], unique=False)
    op.create_index(op.f('ix_clustering_Lon'), 'clustering', ['Lon'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clustering_Lon'), table_name='clustering')
    op.drop_index(op.f('ix_clustering_Lat'), table_name='clustering')
    op.drop_index(op.f('ix_clustering_Label'), table_name='clustering')
    op.drop_index(op.f('ix_clustering_EARF_Number'), table_name='clustering')
    op.drop_table('clustering')
    # ### end Alembic commands ###
