"""empty message

Revision ID: a2876a0d1cdb
Revises: e21b415122fc
Create Date: 2020-11-07 22:11:15.820138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2876a0d1cdb'
down_revision = 'e21b415122fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deployment_evaluation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('EARF_Number', sa.Integer(), nullable=False),
    sa.Column('Lat', sa.Float(), nullable=True),
    sa.Column('Lon', sa.Float(), nullable=True),
    sa.Column('d_current', sa.Float(), nullable=True),
    sa.Column('d_k_means', sa.Float(), nullable=True),
    sa.Column('d_db_180', sa.Float(), nullable=True),
    sa.Column('d_db_60', sa.Float(), nullable=True),
    sa.Column('d_db_40', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployment_evaluation_EARF_Number'), 'deployment_evaluation', ['EARF_Number'], unique=False)
    op.create_index(op.f('ix_deployment_evaluation_Lat'), 'deployment_evaluation', ['Lat'], unique=False)
    op.create_index(op.f('ix_deployment_evaluation_Lon'), 'deployment_evaluation', ['Lon'], unique=False)
    op.create_index(op.f('ix_deployment_evaluation_d_current'), 'deployment_evaluation', ['d_current'], unique=False)
    op.create_index(op.f('ix_deployment_evaluation_d_db_180'), 'deployment_evaluation', ['d_db_180'], unique=False)
    op.create_index(op.f('ix_deployment_evaluation_d_db_40'), 'deployment_evaluation', ['d_db_40'], unique=False)
    op.create_index(op.f('ix_deployment_evaluation_d_db_60'), 'deployment_evaluation', ['d_db_60'], unique=False)
    op.create_index(op.f('ix_deployment_evaluation_d_k_means'), 'deployment_evaluation', ['d_k_means'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deployment_evaluation_d_k_means'), table_name='deployment_evaluation')
    op.drop_index(op.f('ix_deployment_evaluation_d_db_60'), table_name='deployment_evaluation')
    op.drop_index(op.f('ix_deployment_evaluation_d_db_40'), table_name='deployment_evaluation')
    op.drop_index(op.f('ix_deployment_evaluation_d_db_180'), table_name='deployment_evaluation')
    op.drop_index(op.f('ix_deployment_evaluation_d_current'), table_name='deployment_evaluation')
    op.drop_index(op.f('ix_deployment_evaluation_Lon'), table_name='deployment_evaluation')
    op.drop_index(op.f('ix_deployment_evaluation_Lat'), table_name='deployment_evaluation')
    op.drop_index(op.f('ix_deployment_evaluation_EARF_Number'), table_name='deployment_evaluation')
    op.drop_table('deployment_evaluation')
    # ### end Alembic commands ###
