"""empty message

Revision ID: a2ce9d655ac0
Revises: e70d580db7a6
Create Date: 2020-08-29 12:16:41.131624

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a2ce9d655ac0'
down_revision = 'e70d580db7a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ambulance_station',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Location_id', sa.String(length=500), nullable=True),
    sa.Column('Station_Name', sa.String(length=300), nullable=True),
    sa.Column('Status', sa.String(length=100), nullable=True),
    sa.Column('Lat', sa.Float(), nullable=True),
    sa.Column('Lon', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ambulance_station_Lat'), 'ambulance_station', ['Lat'], unique=False)
    op.create_index(op.f('ix_ambulance_station_Location_id'), 'ambulance_station', ['Location_id'], unique=True)
    op.create_index(op.f('ix_ambulance_station_Lon'), 'ambulance_station', ['Lon'], unique=False)
    op.create_index(op.f('ix_ambulance_station_Station_Name'), 'ambulance_station', ['Station_Name'], unique=False)
    op.create_index(op.f('ix_ambulance_station_Status'), 'ambulance_station', ['Status'], unique=False)
    op.create_table('overtime_fa_count',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Final_Assessment_Code', sa.String(length=100), nullable=True),
    sa.Column('Response_Time_Class', sa.Integer(), nullable=True),
    sa.Column('Count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_overtime_fa_count_Count'), 'overtime_fa_count', ['Count'], unique=False)
    op.create_index(op.f('ix_overtime_fa_count_Final_Assessment_Code'), 'overtime_fa_count', ['Final_Assessment_Code'], unique=False)
    op.create_index(op.f('ix_overtime_fa_count_Response_Time_Class'), 'overtime_fa_count', ['Response_Time_Class'], unique=False)
    op.drop_table('top_6_fa')
    op.drop_table('overtime_fa_count_pre')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('overtime_fa_count_pre',
    sa.Column('Final_Assessment_Code', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('Response_Time_Class', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Count', mysql.BIGINT(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('top_6_fa',
    sa.Column('Final_Assessment_Code', mysql.VARCHAR(length=100), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_overtime_fa_count_Response_Time_Class'), table_name='overtime_fa_count')
    op.drop_index(op.f('ix_overtime_fa_count_Final_Assessment_Code'), table_name='overtime_fa_count')
    op.drop_index(op.f('ix_overtime_fa_count_Count'), table_name='overtime_fa_count')
    op.drop_table('overtime_fa_count')
    op.drop_index(op.f('ix_ambulance_station_Status'), table_name='ambulance_station')
    op.drop_index(op.f('ix_ambulance_station_Station_Name'), table_name='ambulance_station')
    op.drop_index(op.f('ix_ambulance_station_Lon'), table_name='ambulance_station')
    op.drop_index(op.f('ix_ambulance_station_Location_id'), table_name='ambulance_station')
    op.drop_index(op.f('ix_ambulance_station_Lat'), table_name='ambulance_station')
    op.drop_table('ambulance_station')
    # ### end Alembic commands ###
