"""empty message

Revision ID: e21b415122fc
Revises: f3016a04f545
Create Date: 2020-10-13 00:35:04.494010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e21b415122fc'
down_revision = 'f3016a04f545'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('k_means_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Lat', sa.Float(), nullable=True),
    sa.Column('Lon', sa.Float(), nullable=True),
    sa.Column('Count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_k_means_result_Count'), 'k_means_result', ['Count'], unique=False)
    op.create_index(op.f('ix_k_means_result_Lat'), 'k_means_result', ['Lat'], unique=False)
    op.create_index(op.f('ix_k_means_result_Lon'), 'k_means_result', ['Lon'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_k_means_result_Lon'), table_name='k_means_result')
    op.drop_index(op.f('ix_k_means_result_Lat'), table_name='k_means_result')
    op.drop_index(op.f('ix_k_means_result_Count'), table_name='k_means_result')
    op.drop_table('k_means_result')
    # ### end Alembic commands ###
