"""empty message

Revision ID: e70d580db7a6
Revises: 157d3c6078a0
Create Date: 2020-08-21 20:07:56.250054

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e70d580db7a6'
down_revision = '157d3c6078a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('overtime_fa_count',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Final_Assessment_Code', sa.String(length=100), nullable=True),
    sa.Column('Response_Time_Class', sa.Integer(), nullable=True),
    sa.Column('Count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_overtime_fa_count_Count'), 'overtime_fa_count', ['Count'], unique=False)
    op.create_index(op.f('ix_overtime_fa_count_Final_Assessment_Code'), 'overtime_fa_count', ['Final_Assessment_Code'], unique=False)
    op.create_index(op.f('ix_overtime_fa_count_Response_Time_Class'), 'overtime_fa_count', ['Response_Time_Class'], unique=False)
    op.drop_table('top_6_fa')
    op.create_index(op.f('ix_final_ass_count_Count'), 'final_ass_count', ['Count'], unique=False)
    op.create_index(op.f('ix_final_ass_count_Final_Assessment'), 'final_ass_count', ['Final_Assessment'], unique=False)
    op.create_index(op.f('ix_response_time_count_Count'), 'response_time_count', ['Count'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_response_time_count_Count'), table_name='response_time_count')
    op.drop_index(op.f('ix_final_ass_count_Final_Assessment'), table_name='final_ass_count')
    op.drop_index(op.f('ix_final_ass_count_Count'), table_name='final_ass_count')
    op.create_table('top_6_fa',
    sa.Column('Final_Assessment_Code', mysql.VARCHAR(length=100), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_overtime_fa_count_Response_Time_Class'), table_name='overtime_fa_count')
    op.drop_index(op.f('ix_overtime_fa_count_Final_Assessment_Code'), table_name='overtime_fa_count')
    op.drop_index(op.f('ix_overtime_fa_count_Count'), table_name='overtime_fa_count')
    op.drop_table('overtime_fa_count')
    # ### end Alembic commands ###
