"""empty message

Revision ID: eb91838dfff4
Revises: f85d22f1a87f
Create Date: 2020-09-11 18:18:28.256631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb91838dfff4'
down_revision = 'f85d22f1a87f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('earf', sa.Column('AMPDS_Code', sa.String(length=100), nullable=True))
    op.add_column('earf', sa.Column('Priority', sa.String(length=100), nullable=True))
    op.add_column('earf', sa.Column('Protocol', sa.Integer(), nullable=False))
    op.add_column('earf', sa.Column('Sub_Category', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_earf_AMPDS_Code'), 'earf', ['AMPDS_Code'], unique=False)
    op.create_index(op.f('ix_earf_Priority'), 'earf', ['Priority'], unique=False)
    op.create_index(op.f('ix_earf_Protocol'), 'earf', ['Protocol'], unique=False)
    op.create_index(op.f('ix_earf_Sub_Category'), 'earf', ['Sub_Category'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_earf_Sub_Category'), table_name='earf')
    op.drop_index(op.f('ix_earf_Protocol'), table_name='earf')
    op.drop_index(op.f('ix_earf_Priority'), table_name='earf')
    op.drop_index(op.f('ix_earf_AMPDS_Code'), table_name='earf')
    op.drop_column('earf', 'Sub_Category')
    op.drop_column('earf', 'Protocol')
    op.drop_column('earf', 'Priority')
    op.drop_column('earf', 'AMPDS_Code')
    # ### end Alembic commands ###
