"""empty message

Revision ID: f0dcedda439c
Revises: a2ce9d655ac0
Create Date: 2020-08-31 13:48:54.746707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0dcedda439c'
down_revision = 'a2ce9d655ac0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_case_count',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Date', sa.DateTime(), nullable=True),
    sa.Column('Count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_case_count_Count'), 'daily_case_count', ['Count'], unique=False)
    op.create_index(op.f('ix_daily_case_count_Date'), 'daily_case_count', ['Date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_case_count_Date'), table_name='daily_case_count')
    op.drop_index(op.f('ix_daily_case_count_Count'), table_name='daily_case_count')
    op.drop_table('daily_case_count')
    # ### end Alembic commands ###
