"""empty message

Revision ID: f85d22f1a87f
Revises: f0dcedda439c
Create Date: 2020-09-01 11:14:46.860678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f85d22f1a87f'
down_revision = 'f0dcedda439c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_case_count',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Date', sa.DateTime(), nullable=True),
    sa.Column('Count', sa.Integer(), nullable=False),
    sa.Column('Overtime_Count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_case_count_Count'), 'daily_case_count', ['Count'], unique=False)
    op.create_index(op.f('ix_daily_case_count_Date'), 'daily_case_count', ['Date'], unique=False)
    op.create_index(op.f('ix_daily_case_count_Overtime_Count'), 'daily_case_count', ['Overtime_Count'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_case_count_Overtime_Count'), table_name='daily_case_count')
    op.drop_index(op.f('ix_daily_case_count_Date'), table_name='daily_case_count')
    op.drop_index(op.f('ix_daily_case_count_Count'), table_name='daily_case_count')
    op.drop_table('daily_case_count')
    # ### end Alembic commands ###
